reset

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -1,96 +1,148 @@
+---
 stages:
-- name: Build Stage
+- name: BUILD
   inputs:
   - type: git
     branch: master
-    service: ${REPO}
+    service: ${GIT_REPO}    
+  triggers:
+  - type: commit
   jobs:
-  - name: Container Build
+  - name: Container build
     type: builder
-    artifact_dir: ''
-    build_type: shell
-    script: |-
+    extension_id: ibm.devops.services.pipeline.container.builder
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+    IMAGE_NAME: ${CF_APP_NAME}
+    USE_CACHED_LAYERS: 'true'
+    COMMAND: |
       #!/bin/bash
-
-      ###########################################################
-      # Install Docker                                          #
-      ###########################################################
-      install_docker_run_build() {
-          echo "installing docker"
-          echo "TMPDIR: ${TMPDIR}"
-          sudo apt-get -y install apt-transport-https ca-certificates &> $TMPDIR/dockerinst.out
-          sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &>> $TMPDIR/dockerinst.out
-          sudo add-apt-repository "deb https://apt.dockerproject.org/repo ubuntu-precise main" &>> $TMPDIR/dockerinst.out
-          sudo apt-get update &>> $TMPDIR/dockerinst.out
-          sudo apt-get -y install docker-engine &>> $TMPDIR/dockerinst.out
-          local RESULT=$?
-          if [ $RESULT -ne 0 ]; then
-              echo "Installing docker.io failed with return code ${RESULT}"
-              cat $TMPDIR/dockerinst.out
-              sudo apt-get -y install docker.engine &> $TMPDIR/dockerinst.out
+      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.  
+      echo -e "${label_color}Starting build script${no_color}"
+      
+      # The IBM Container Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have been installed.
+      # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix 
+      #####################
+      # Run unit tests    #
+      #####################
+      echo -e "${label_color}No unit tests cases have been checked in ${no_color}"
+      
+      ######################################
+      # Build Container via Dockerfile     #
+      ######################################
+      
+      # REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
+      # FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}   
+      
+      # Possible adding retries to build the image
+      if [ -f Dockerfile ]; then 
+          echo -e "${label_color}BUILDING ${FULL_REPOSITORY_NAME} ${no_color}"
+          ${EXT_DIR}/utilities/sendMessage.sh -l info -m "New container build requested for ${FULL_REPOSITORY_NAME}"
+          # build image
+          BUILD_COMMAND=""
+          if [ "${USE_CACHED_LAYERS}" == "true" ]; then 
+              BUILD_COMMAND="build --pull --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
+              ice_retry ${BUILD_COMMAND}
               RESULT=$?
-              if [ $RESULT -ne 0 ]; then
-                  echo "Installing docker.engine failed with return code ${RESULT}"
-                  cat $TMPDIR/dockerinst.out
-                  return 1
-              fi
-          fi
-          DOCKER_VER=$(docker -v)
-          echo "Successfully installed ${DOCKER_VER}"
-
-          IMAGE_NAME=ddcao-5sep-529
-          REGISTRY_URL=registry.stage1.ng.bluemix.net/ddcao_5sep_namespace
-          FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:v1.0.0
-
-          echo "FULL_REPOSITORY_NAME: ${FULL_REPOSITORY_NAME}"
-          
-          if [ -f Dockerfile ]; then 
-            # build image
-            echo "BUILDING Dockerfile"
-
-            docker build -t "${FULL_REPOSITORY_NAME}" .
-
-            echo "BUILDING Dockerfile finished"
-
-            docker push "${FULL_REPOSITORY_NAME}"
           else 
-            echo "Dockerfile not found at the repository root"
-            exit 1
-          fi
-      }
-
-      install_docker_run_build
-  - name: Post Build
-    type: builder
-    artifact_dir: ''
-    build_type: shell
-    script: |-
+              BUILD_COMMAND="build --no-cache --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
+              ice_retry ${BUILD_COMMAND}
+              RESULT=$?
+          fi 
+      
+          if [ $RESULT -ne 0 ]; then
+              echo -e "${red}Error building image ${no_color}" | tee -a "$ERROR_LOG_FILE"
+              echo "Build command: ice ${BUILD_COMMAND}"
+              ice info 
+              ice images
+              ${EXT_DIR}/print_help.sh
+              ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Container build of ${FULL_REPOSITORY_NAME} failed"
+              exit 1
+          else
+              ${EXT_DIR}/utilities/sendMessage.sh -l good -m "Container build of ${FULL_REPOSITORY_NAME} was successful"
+              echo -e "${green}Container build of ${FULL_REPOSITORY_NAME} was successful ${no_color}"
+          fi  
+      else 
+          echo -e "${red}Dockerfile not found at the repository root${no_color}"
+          exit 1
+      fi  
+      
+      ######################################################################################
+      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
+      ######################################################################################
+      echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
+      if [ -f deployment.yml ]; then
+          #Update deployment.yml with image name
+          echo "UPDATING DEPLOYMENT MANIFEST:"
+          sed -i "s~^\([[:blank:]]*\)image:.*$~\1image: ${FULL_REPOSITORY_NAME}~" deployment.yml
+          cat deployment.yml
+          cp deployment.yml $ARCHIVE_DIR/
+      else 
+          echo -e "${red}Kubernetes deployment file 'deployment.yml' not found at the repository root${no_color}"
+          exit 1
+      fi      
+- name: VALIDATE
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Container build
+  triggers:
+  - type: stage
+  properties:
+  - name: FULL_REPOSITORY_NAME
+    value: ''
+    type: text  
+  jobs:
+  - name: Vulnerability Advisor
+    type: tester
+    extension_id: ibm.devops.services.pipeline.crawler.tester
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+    WAIT_TIME: '5'
+- name: DEPLOY
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Container build
+  jobs:
+  - name: Deploy Kubernetes Pod
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
       #!/bin/bash
-      if  [[ -f post_build.sh ]]; then
-        chmod +x post_build.sh;
-        echo "executing the post_build script";
-        sh post_build.sh;
-      else
-        echo "the post_build script does not exist";
-      fi
-# - name: Deploy Stage
-#   inputs:
-#   - type: job
-#     stage: Build Stage
-#     job: Container Build
-#   triggers:
-#   - type: stage
-#   jobs:
-#   - name: Deploy
-#     type: deployer
-#     target:
-#       region_id: ${CF_REGION_ID}
-#       organization: ${CF_ORGANIZATION}
-#       space: ${CF_SPACE}
-#     script: |
-#       #!/bin/bash
-#       #set -x
+      #set -x
 
-#       helm init
-#       helm install ./chart/ddcaocoolapp
-#       echo "finished installing chart"
+      #Check cluster availability
+      ip_addr=$(bx cs workers $PIPELINE_KUBERNETES_CLUSTER_NAME | grep normal | awk '{ print $2 }')
+      if [ -z $ip_addr ]; then
+        echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
+        exit 1
+      fi
+
+      #Connect to a different container-service api by uncommenting and specifying an api endpoint
+      #bx cs init --host https://us-south.containers.bluemix.net
+      echo ""
+      echo "DEPLOYING USING MANIFEST:"
+      cat deployment.yml
+      kubectl apply -f deployment.yml  
+
+      echo ""
+      echo "DEPLOYED SERVICE:"
+      kubectl describe services hello-service
+
+      echo ""
+      echo "DEPLOYED PODS:"
+      kubectl describe pods --selector app=hello-app
+
+      port=$(kubectl get services | grep hello-service | sed 's/.*:\([0-9]*\).*/\1/g')
+      echo ""
+      echo "VIEW THE APPLICATION AT: http://$ip_addr:$port"
