add docker install

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -11,6 +11,35 @@ stages:
     build_type: shell
     script: |-
       #!/bin/bash
+
+      ###########################################################
+      # Install Docker                                          #
+      ###########################################################
+      install_docker() {
+          echo "installing docker"
+          echo "EXT_DIR: ${EXT_DIR}"
+          sudo apt-get -y install apt-transport-https ca-certificates &> $EXT_DIR/dockerinst.out
+          sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &>> $EXT_DIR/dockerinst.out
+          sudo add-apt-repository "deb https://apt.dockerproject.org/repo ubuntu-precise main" &>> $EXT_DIR/dockerinst.out
+          sudo apt-get update &>> $EXT_DIR/dockerinst.out
+          sudo apt-get -y install docker-engine &>> $EXT_DIR/dockerinst.out
+          local RESULT=$?
+          if [ $RESULT -ne 0 ]; then
+              echo "Installing docker.io failed with return code ${RESULT}"
+              cat $EXT_DIR/dockerinst.out
+              sudo apt-get -y install docker.engine &> $EXT_DIR/dockerinst.out
+              RESULT=$?
+              if [ $RESULT -ne 0 ]; then
+                  echo "Installing docker.engine failed with return code ${RESULT}"
+                  cat $EXT_DIR/dockerinst.out
+                  return 1
+              fi
+          fi
+          DOCKER_VER=$(docker -v)
+          echo "Successfully installed ${DOCKER_VER}"
+      }
+
+      install_docker
       
       IMAGE_NAME=ddcao-5sep-529
       REGISTRY_URL=registry.stage1.ng.bluemix.net/ddcao_5sep_namespace
